<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Jalalabad</name>
   <tag></tag>
   <elementGuidId>d3d9512f-f09b-4364-8c0a-fffaffe74c4a</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/status/79660093-7993-4617-888d-68f0ca185301</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Jalalabad</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;qa-Application-content&quot;]/div[1]/div[1]/div[5]/div[@class=&quot;qa-DataPackPage-view&quot;]/div[1]/div[1]/div[1]/div[1]/div[@class=&quot;qa-MapView-GridList&quot;]/div[1]/div[@class=&quot;qa-DataPackListItem-Card&quot;]/div[1]/div[@class=&quot;qa-DataPackListItem-CardTitle&quot;]/span[1]/div[1]/div[1]/div[@class=&quot;qa-DataPackListItem-titleLink&quot;]/a[1]</value>
   </webElementProperties>
</WebElementEntity>
