<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_MEMBERS (0)</name>
   <tag></tag>
   <elementGuidId>777ea58d-226c-4920-8c72-5c4a25cc1ac3</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>MEMBERS (0)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[12]/div[@class=&quot;qa-ShareBaseDialog-Dialog&quot;]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[@class=&quot;qa-DataPackShareDialog-container&quot;]/div[@class=&quot;qa-DataPackShareDialog-headers&quot;]/div[@class=&quot;qa-DataPackShareDialog-RaisedButton-members&quot;]/button[1]</value>
   </webElementProperties>
</WebElementEntity>
