<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Share</name>
   <tag></tag>
   <elementGuidId>fc97b7df-bac5-4669-b317-b1a0623b3e74</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Share</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[12]/div[1]/div[1]/div[1]/div[1]/div[1]/div[4]/span[@class=&quot;qa-DataPackListItem-MenuItem-share&quot;]/div[1]/div[1]/div[1]</value>
   </webElementProperties>
</WebElementEntity>
