<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Enter General InformationD</name>
   <tag></tag>
   <elementGuidId>77dabdbb-eb9d-4ef9-bb0e-35cad6eaeb5d</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>paper</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>qa-ExportInfo-Paper</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Enter General InformationDatapack Name90DescriptionProject NameSelect Data SourcesYou must choose at least oneDATA PROVIDERSAVAILABILITYRUN AVAILABILITY CHECK AGAINYou may try to resolve errors by running the availability check again.Aster Elevation (V2)SuccessNo problems: Export should proceed without issues.DigitalGlobe Imagery (Foundation GEOINT)SuccessNo problems: Export should proceed without issues.DigitalGlobe (ImageryTileService)SuccessNo problems: Export should proceed without issues.NOMESuccessNo problems: Export should proceed without issues.OpenStreetMap Data (Themes)SuccessNo problems: Export should proceed without issues.OpenStreetMap TilesSuccessNo problems: Export should proceed without issues.Select ProjectionEPSG:4326 - World Geodetic System 1984 (WGS84)Area of Interest (AOI)Area0 sq kmSelected Area of InterestEdit</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;paper&quot;)</value>
   </webElementProperties>
</WebElementEntity>
