<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Delaplane</name>
   <tag></tag>
   <elementGuidId>97123462-31ac-456f-984e-cef2e9cd04eb</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>qa-TypeaheadMenuItem-name</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Delaplane</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;map&quot;)/div[1]/div[@class=&quot;typeahead__typeahead___1wiGm&quot;]/div[@class=&quot;bootstrap-typeahead open&quot;]/ul[@class=&quot;dropdown-menu bootstrap-typeahead-menu dropdown-menu-justify&quot;]/li[@class=&quot;typeahead__menuItem___3pFVN&quot;]/a[1]/div[@class=&quot;row&quot;]/div[2]/div[@class=&quot;qa-TypeaheadMenuItem-name&quot;]</value>
   </webElementProperties>
</WebElementEntity>
